# Intro to Numpy

[Here](http://cs231n.github.io/python-numpy-tutorial/#python-sets) is a Numpy tutorial.

**Numpy** is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 
A **numpy array** is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the **rank** of the array; the **shape** of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np
import pandas as pd

## Vectors

In [2]:
# A vector:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [3]:
type(v)

numpy.ndarray

In [4]:
list(v)

[1, 2, 3]

In [5]:
v[0]

1

In [6]:
# Dot product of two vectors:
w = np.array([100,10,1])

print(np.dot(v, w))

123


## Matrices

In [7]:
#A matrix:
m = np.array([[0,1],[2,3]])
m

array([[0, 1],
       [2, 3]])

In [8]:
print(m)

[[0 1]
 [2 3]]


In [9]:
m[1,1]

3

In [10]:
m[1,1]=4
m

array([[0, 1],
       [2, 4]])

In [11]:
print(m.shape)            #Dimension of the array

(2, 2)


In [12]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [14]:
(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(1, 2, 4)

In [15]:
#Matrix times vector:
m = np.array([[1,10],[100,1000]])
v = np.array([1,2])
np.dot(m, v)

array([  21, 2100])

In [16]:
#Matrix times matrix:
m1 = np.array([[1,2],[3,4],[5,6]])
m2 = np.array([[5,6],[7,8]])
np.dot(m1, m2)

array([[19, 22],
       [43, 50],
       [67, 78]])

## Descriptive statistics

In [17]:
df = pd.read_csv('../datasets/GDP-2015.csv')
gdp = df['GDP per capita']

In [18]:
import numpy
print( "Mean GDP is", np.mean(gdp) )
print( "Standard deviation is", np.std(gdp) )
print( "Count is", np.count_nonzero(gdp) )
print( "Minimum GDP is", min(gdp) )
print( "Maximum GDP is", max(gdp) )
print( "25 percentile of GDP is", np.percentile(gdp, 25) )
print( "50 percentile of GDP is", np.percentile(gdp, 50) )
print( "75 percentile of GDP is", np.percentile(gdp, 75) )
print( "Sum is", np.sum(gdp) )
print( "Median is", np.median(gdp) )

Mean GDP is 18194.47619047619
Standard deviation is 19192.237408635632
Count is 168
Minimum GDP is 605
Maximum GDP is 139542
25 percentile of GDP is 3714.0
50 percentile of GDP is 11794.0
75 percentile of GDP is 25816.5
Sum is 3056672
Median is 11794.0


## Random numbers

In [19]:
np.random.rand()

0.2934491224010284

In [20]:
np.random.rand(10)

array([0.22041805, 0.22442446, 0.76974535, 0.26690575, 0.54418142,
       0.20671742, 0.6240694 , 0.03370039, 0.0806832 , 0.20599073])